version: 2
jobs:
  build:
    machine:
      enabled: true
      # https://circleci.com/docs/2.0/executor-types/#using-machine
      # docker 17.03.0-ce, docker-compose 1.9.0
      image: circleci/classic:latest
    working_directory: ~/easy_django_mockups
    steps:
      - checkout
      - run: virtualenv venv
      - run: pip install Django==1.11
      - run: pip install tox
      - run: tox
